[project]
authors = ["schneiderlin <positivevector@gmail.com>"]
channels = ["conda-forge"]
name = "python-stuff"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
openai = ">=1.76.0,<2"
python-dotenv = ">=1.1.0,<2"
